repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        # Black should pick up its configuration from pyproject.toml

      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
        # isort should pick up its configuration from pyproject.toml

      - id: ruff-format
        name: ruff-format
        entry: poetry run ruff format
        language: system
        types: [python]
        # ruff format should pick up its configuration from pyproject.toml

      - id: ruff-lint
        name: ruff-lint
        # Using --fix so it attempts to auto-correct lint issues during pre-commit
        entry: poetry run ruff check --fix
        language: system
        types: [python]
        # ruff lint should pick up its configuration from pyproject.toml
