services:
  hplc-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: hplc-bo-dev
    container_name: hplc-bo-dev
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    # Command is now defined in Dockerfile.dev
    platform: linux/amd64  # Optional: force x86_64 for M1/arm64 hosts
    ports:
      - "8501:8501"  # Expose Streamlit port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '14.0'   # Use up to 10 CPU cores (out of 12 available)
          memory: 16G     # Use up to 16GB of memory
        reservations:
          cpus: '12.0'    # Reserve at least 12 CPU cores
          memory: 12G      # Reserve at least GB of memory
