services:
  hplc-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: hplc-bo-dev
    container_name: hplc-bo-dev
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: sleep infinity
    platform: linux/amd64  # Optional: force x86_64 for M1/arm64 hosts
    deploy:
      resources:
        limits:
          cpus: '14.0'   # Use up to 10 CPU cores (out of 12 available)
          memory: 16G     # Use up to 16GB of memory
        reservations:
          cpus: '12.0'    # Reserve at least 12 CPU cores
          memory: 12G      # Reserve at least GB of memory
