version: "3.8"
services:
  hplc-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: hplc-bo-dev
    container_name: hplc-bo-dev
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: sleep infinity
    platform: linux/amd64  # for M1/arm64 hosts, this ensures x86_64 build
