services:
  hplc-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: hplc-bo-dev
    container_name: hplc-bo-pycharm
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: sleep infinity
